// Fake filesystem for NS Doors 97

export type FsFileType = "text" | "exe" | "bat" | "sys" | "scr" | "drv" | "tmp" | "zip" | "bmp" | "ini";

export interface FsFile {
  kind: "file";
  name: string;
  type: FsFileType;
  content?: string;      // text files
  action?: string;       // exe: maps to a window/experience id, or "noop"
}

export interface FsFolder {
  kind: "folder";
  name: string;
  children: FsNode[];
}

export type FsNode = FsFile | FsFolder;

// ── Text content ─────────────────────────────────────────────────────────────

const README = `WELCOME TO NS DOORS 97
======================
Thank you for purchasing NS Doors 97 by Noahsoft Corporation.

SYSTEM REQUIREMENTS:
  - 486 DX2 66 MHz or faster
  - 8 MB RAM (16 MB recommended)
  - 200 MB free disk space
  - VGA or better display (640x480, 256 colors)

GETTING STARTED:
Double-click any icon on the desktop to launch a program.
Right-click for options (coming soon in NS Doors 98!).

SUPPORT:
Call 1-800-NOAHSOFT between 9AM-5PM EST, Mon-Fri.
Long distance charges may apply.

(c) 1997 Noahsoft Corporation. All rights reserved.
Unauthorized duplication is prohibited by law.
`;

const LETTER_MOM = `October 14, 1997

Dear Mom,

I finally got the computer set up! It only took three days and
I only called tech support twice. The man named Gerald was very
patient with me about the CD-ROM situation.

NS Doors 97 is really something. You should see the screensaver.
It looks like actual stars flying at you. I nearly fell out of
my chair the first time it came on.

Dad keeps wanting to use it to look up fishing lures on the
internet. I told him the internet costs by the minute so he
needs to be quick about it.

Can you send the recipe for that casserole? I'll type it up
and keep it on the computer. Very modern.

Love,
Noah

P.S. Tell Dad the fishing lure website is probably on America
Online. We got a free disc in the mail.
`;

const TODO = `TODO LIST - Updated 10/22/1997
================================
[x] Figure out how to print (call Gerald again)
[x] Set up the screensaver
[ ] Learn how to make a spreadsheet
[ ] Get Dad's fishing lure website bookmarked
[ ] Find out what a "cookie" is (the computer kind)
[ ] Back up important files to floppy disk
[ ] Ask about that Y2K thing everyone's talking about
[ ] DEFRAG the hard drive (Gerald said every month)
[ ] Write letter to Grandma on the computer
[ ] Make a family budget spreadsheet (in progress - see Budget97.txt)
[ ] Find Minesweeper tips on the internet
`;

const BUDGET = `FAMILY BUDGET - FISCAL YEAR 1997
==================================

INCOME:
  Noah's salary:          $2,400 / mo
  Side work (odd jobs):     $150 / mo
  TOTAL INCOME:           $2,550 / mo

EXPENSES:
  Rent:                     $650 / mo
  Groceries:                $280 / mo
  Car payment:              $215 / mo
  Car insurance:             $94 / mo
  Phone (long distance!):    $67 / mo   <- call Mom less (sorry Mom)
  Electric:                  $58 / mo
  Internet dial-up (AOL):    $21.95 / mo
  Cable TV:                  $35 / mo
  Misc / fun money:         $100 / mo
  TOTAL EXPENSES:         $1,520.95 / mo

SAVINGS:                  $1,029.05 / mo

NOTES:
- Remember internet is PER MINUTE after first 10 hours!
  DO NOT leave AOL connected and walk away again.
- Christmas gifts budget: $200 total (stick to it this year)
- Computer cost $1,899 — paid off by February at this rate
`;

const DIARY = `PERSONAL DIARY - DO NOT READ - SERIOUSLY
=========================================

Sept 3, 1997
Got the computer today. It's enormous. Had to rearrange the whole
desk. The monitor alone weighs as much as a small child.

Sept 5, 1997
Finally got it to turn on properly. The startup sound scared
the cat. She hasn't come back in the room since.

Sept 8, 1997
Found a website with jokes. Printed 47 of them. Ink cartridge
now empty. This is going to be an expensive hobby.

Sept 19, 1997
Played Solitaire for 3 hours. The computer is supposed to make
me more productive.

Oct 2, 1997
Got NS Doors 97 upgrade disc in the mail. Took all day to install.
Gerald at tech support says I am his "most interesting caller."
I'm not sure that's a compliment.

Oct 14, 1997
Wrote a letter to Mom. On the COMPUTER. Didn't even need to
use white-out. This changes everything.

Oct 22, 1997
Figured out what a browser is. The internet is just full of
people arguing about Star Trek and selling used cars.
I feel prepared for the future.
`;

const CONFIG_SYS = `@REM NS DOORS 97 SYSTEM CONFIGURATION
@REM Generated by NS Doors 97 Setup - DO NOT EDIT

DEVICE=C:\\SYSTEM\\DRIVERS\\HIMEM.SYS
DEVICE=C:\\SYSTEM\\DRIVERS\\EMM386.EXE NOEMS
BUFFERS=40,0
FILES=85
LASTDRIVE=Z
FCBS=4,0
DOS=HIGH,UMB
STACKS=9,256
SHELL=C:\\SYSTEM\\COMMAND.COM /P /E:2048
`;

const AUTOEXEC = `@ECHO OFF
PROMPT $P$G
PATH C:\\SYSTEM;C:\\PROGRAMS;C:\\PROGRAMS\\ACCESSORIES
SET TEMP=C:\\SYSTEM\\TEMP
SET TMP=C:\\SYSTEM\\TEMP
SET BLASTER=A220 I5 D1 H5 P330 T6
SMARTDRV /X
MODE CON RATE=32 DELAY=1
@REM Uncomment below to load mouse driver
@REM C:\\SYSTEM\\DRIVERS\\MOUSE.COM /Y
ECHO Welcome to NS Doors 97.
`;

const WIN_INI = `[windows]
spooler=yes
load=
run=
Beep=yes
NullPort=None
BorderWidth=3
CursorBlinkRate=530
DoubleClickSpeed=452
Programs=com exe bat pif
Documents=txt doc

[Desktop]
Wallpaper=(None)
TileWallpaper=0
WallpaperStyle=0
Pattern=(None)

[Noahsoft]
Version=97.2.1
SerialNumber=NS97-4821-XXXX-9901
RegisteredUser=Noah Wright
RegisteredOrganization=Home

[sounds]
SystemStart=C:\\SYSTEM\\sounds\\startup.wav
SystemExit=C:\\SYSTEM\\sounds\\shutdown.wav
SystemHand=C:\\SYSTEM\\sounds\\error.wav

[mci extensions]
wav=waveaudio
mid=sequencer
`;

const SYSTEM_INI = `[boot]
shell=nsdoors.exe
mouse.drv=C:\\SYSTEM\\DRIVERS\\mouse.drv
display.drv=C:\\SYSTEM\\DRIVERS\\svga256.drv
sound.drv=C:\\SYSTEM\\DRIVERS\\sound.drv
comm.drv=C:\\SYSTEM\\DRIVERS\\comm.drv

[386Enh]
woafont=dosapp.fon
EGA80WOA.FON=EGA80WOA.FON
MinTimeSlice=20
WinTimeSlice=100,50
mouse=*vmouse
keyboard=*vkd
MaxBPs=768
`;

const RECYCLE_DRAFT = `Draft letter - never sent

June 3, 1997

To whom it may concern at Noahsoft Corporation,

I am writing to express my frustration with NS Doors 95.
The hourglass cursor appears for no reason. My files rearrange
themselves. The computer told me I performed an "illegal operation"
and I have done nothing of the sort.

I demand to speak with someone in charge.

Sincerely,
A Very Patient Customer

---
[NOTE TO SELF: Don't send this. Gerald has been very nice.
And NS Doors 97 is actually pretty good. Delete this.]
`;

// ── Filesystem tree ───────────────────────────────────────────────────────────

export const ROOT: FsFolder = {
  kind: "folder",
  name: "C:\\",
  children: [
    {
      kind: "folder",
      name: "Documents",
      children: [
        { kind: "file", name: "readme.txt",           type: "text", content: README         },
        { kind: "file", name: "Letter to Mom.txt",    type: "text", content: LETTER_MOM     },
        { kind: "file", name: "Todo.txt",             type: "text", content: TODO           },
        { kind: "file", name: "Budget 1997.txt",      type: "text", content: BUDGET         },
        { kind: "file", name: "Secret Diary.txt",     type: "text", content: DIARY          },
      ],
    },
    {
      kind: "folder",
      name: "Programs",
      children: [
        {
          kind: "folder",
          name: "Games",
          children: [
            { kind: "file", name: "Tic-Tac-Toe.exe",    type: "exe", action: "tic-tac-toe"    },
            { kind: "file", name: "Word Whirlwind.exe",  type: "exe", action: "word-whirlwind" },
            { kind: "file", name: "Number Muncher.exe",  type: "exe", action: "number-muncher" },
            { kind: "file", name: "Cards.exe",           type: "exe", action: "cards"          },
            { kind: "file", name: "Solitaire.exe",       type: "exe", action: "noop"           },
            { kind: "file", name: "Minesweeper.exe",     type: "exe", action: "noop"           },
            { kind: "file", name: "SkiFree.exe",         type: "exe", action: "noop"           },
          ],
        },
        {
          kind: "folder",
          name: "Accessories",
          children: [
            { kind: "file", name: "Notebook.exe",    type: "exe", action: "notebook"   },
            { kind: "file", name: "Paint.exe",       type: "exe", action: "noop"       },
            { kind: "file", name: "Calculator.exe",  type: "exe", action: "noop"       },
            { kind: "file", name: "Clock.exe",       type: "exe", action: "noop"       },
          ],
        },
        {
          kind: "folder",
          name: "Internet",
          children: [
            { kind: "file", name: "Internet Explorer.exe", type: "exe", action: "internet" },
            { kind: "file", name: "Netscape Navigator.exe", type: "exe", action: "noop"    },
            { kind: "file", name: "WinZip.exe",            type: "exe", action: "noop"     },
          ],
        },
        {
          kind: "folder",
          name: "Screensavers",
          children: [
            { kind: "file", name: "Starfield.scr",       type: "scr", action: "starfield"       },
            { kind: "file", name: "Fireworks.scr",       type: "scr", action: "fireworks"       },
            { kind: "file", name: "Bouncing Shapes.scr", type: "scr", action: "bouncing-shapes" },
            { kind: "file", name: "Flying Toasters.scr", type: "scr", action: "noop"            },
          ],
        },
      ],
    },
    {
      kind: "folder",
      name: "System",
      children: [
        { kind: "file", name: "config.sys",    type: "sys", content: CONFIG_SYS  },
        { kind: "file", name: "autoexec.bat",  type: "bat", content: AUTOEXEC    },
        { kind: "file", name: "win.ini",       type: "ini", content: WIN_INI     },
        { kind: "file", name: "system.ini",    type: "ini", content: SYSTEM_INI  },
        {
          kind: "folder",
          name: "Drivers",
          children: [
            { kind: "file", name: "mouse.drv",   type: "drv", action: "noop" },
            { kind: "file", name: "display.drv", type: "drv", action: "noop" },
            { kind: "file", name: "sound.drv",   type: "drv", action: "noop" },
            { kind: "file", name: "comm.drv",    type: "drv", action: "noop" },
          ],
        },
        {
          kind: "folder",
          name: "Temp",
          children: [
            { kind: "file", name: "~tmp0001.tmp", type: "tmp", action: "noop" },
            { kind: "file", name: "~tmp0002.tmp", type: "tmp", action: "noop" },
            { kind: "file", name: "~tmp0087.tmp", type: "tmp", action: "noop" },
          ],
        },
      ],
    },
    {
      kind: "folder",
      name: "Downloads",
      children: [
        { kind: "file", name: "netscape_40_setup.exe", type: "exe", action: "noop" },
        { kind: "file", name: "clipart_pack_vol2.zip", type: "zip", action: "noop" },
        { kind: "file", name: "cool_space_wallpaper.bmp", type: "bmp", action: "noop" },
        { kind: "file", name: "AUTORUN.INF", type: "ini", action: "noop" },
      ],
    },
    {
      kind: "folder",
      name: "Recycle Bin",
      children: [
        { kind: "file", name: "old_draft.txt",        type: "text", content: RECYCLE_DRAFT },
        { kind: "file", name: "budget_old_1996.txt",  type: "text",
          content: "1996 budget - SUPERSEDED\n\nSee Budget 1997.txt for current version.\n" },
        { kind: "file", name: "ns95_uninstall.exe",   type: "exe",  action: "noop" },
      ],
    },
  ],
};

// ── Helpers ───────────────────────────────────────────────────────────────────

export const FILE_TYPE_ICONS: Record<FsFileType | "folder", string> = {
  folder: "📁",
  text:   "📄",
  exe:    "⚙️",
  bat:    "📜",
  sys:    "🔧",
  scr:    "🖥️",
  drv:    "🔩",
  tmp:    "🗒️",
  zip:    "📦",
  bmp:    "🖼️",
  ini:    "📋",
};

export function getNodeIcon(node: FsNode): string {
  if (node.kind === "folder") return FILE_TYPE_ICONS.folder;
  return FILE_TYPE_ICONS[node.type] ?? "📄";
}

export function isReadable(node: FsFile): boolean {
  return node.content !== undefined;
}

// Build path string for a node given its ancestors
export function buildPath(ancestors: string[], name: string): string {
  if (ancestors.length === 0) return name;
  return ancestors.join("\\") + "\\" + name;
}
